console.log(typeof("Oi, meu nome é Ciro"))
console.log('Eu queria comprar um carro')
console.log(typeof('Eu queria comprar um carro'))
console.log(`teste`)
console.log(typeof(`teste`))
console.log(`Infinity`)
console.log(typeof(`Infinity`))
console.log(Infinity)
console.log(typeof(Infinity))