console.log("Primeira linha \nSegunda Linha")
console.log("O meu nome é 'Ciro'")
console.log('O meu nome é "Ciro"')
console.log(`A multiplicação de 5 por 3 é ${5*3}`)
console.log("O " + "meu " +"nome" +" é " + "Ciro")